import gradio as gr
import requests

GITHUB_REPO = "wuzbak/Unitary-Manifold-"

custom_css = """
:root { --az-bg: #0B0F13; --az-panel: #111820; --az-amber: #FF9F00; --az-teal: #4DD0E1; --az-text: #E0E0E0; --az-muted: #8B949E; --az-border: #1F2933; }
.gradio-container { background: var(--az-bg) !important; color: var(--az-text) !important; font-family: 'Inter', system-ui, sans-serif !important; }
.gradio-container h1, .gradio-container h2 { font-family: 'JetBrains Mono', monospace !important; color: var(--az-amber) !important; }
.gradio-container .gr-block { background: var(--az-panel) !important; border: 1px solid var(--az-border) !important; border-radius: 0 !important; }
.gradio-container .gr-button-primary { background: var(--az-amber) !important; color: var(--az-bg) !important; border: none !important; border-radius: 0 !important; font-family: 'JetBrains Mono', monospace !important; text-transform: uppercase !important; }
"""

with gr.Blocks(css=custom_css, title="Corporate — AxiomZero") as app:
    gr.HTML('<div style="text-align:center;padding:2rem 0;border-bottom:2px solid #FF9F00;margin-bottom:1rem;"><h1 style="font-size:2.5rem;color:#FF9F00 !important;font-family:JetBrains Mono,monospace !important;margin:0;">AXIOMZERO</h1><div style="color:#4DD0E1;font-family:monospace;font-size:0.85rem;letter-spacing:0.1em;margin-top:0.5rem;">TECHNOLOGIES & CONSULTING, SPC</div></div>')
    with gr.Tabs():
        with gr.Tab("CHARTER"):
            gr.HTML('<div style="color:#E0E0E0;line-height:1.8;max-width:800px;margin:0 auto;"><h2 style="color:#FF9F00;">Corporate Identity</h2><p><b>AxiomZero Technologies & Consulting, SPC</b> is a Washington State Social Purpose Corporation (SPC) advancing the Unitary Manifold Framework.</p><h3 style="color:#4DD0E1;">Mission</h3><p>Dual mandate: (1) empower the admin with tools, governance, and automation; (2) empower the public with meaningful tools and understanding.</p><h3 style="color:#4DD0E1;">Ethical Stance</h3><p>Pro-humanity and pro-individual. Willing to be abrasive or subversive toward institutions that harm human rights.</p><h3 style="color:#4DD0E1;">Structure</h3><ul><li><b>Type:</b> Social Purpose Corporation (SPC)</li><li><b>State:</b> Washington</li><li><b>HQ:</b> Duvall, WA</li><li><b>Founded:</b> 2026</li><li><b>Contact:</b> cpo@axiomzerospc.org</li><li><b>Website:</b> <a href="https://axiomzerospc.org" style="color:#FF9F00;">axiomzerospc.org</a></li></ul></div>')
        with gr.Tab("PENTAD"):
            gr.HTML('<div style="color:#E0E0E0;line-height:1.8;max-width:800px;margin:0 auto;"><h2 style="color:#FF9F00;">Pentad Governance</h2><p>5-sector distributed authority framework with cross-sector attestation using SHA-256 state hashing.</p><table style="width:100%;border-collapse:collapse;font-size:0.9rem;"><tr style="border-bottom:1px solid #1F2933;"><th style="text-align:left;padding:0.5rem;color:#FF9F00;">Sector</th><th style="text-align:left;padding:0.5rem;color:#FF9F00;">Domain</th></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;color:#4DD0E1;">Computational</td><td style="padding:0.5rem;">Logic, verification, Lean4</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;color:#4DD0E1;">Relational</td><td style="padding:0.5rem;">Data flow, entity relationships</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;color:#4DD0E1;">Intentional</td><td style="padding:0.5rem;">Goal routing, agent orchestration</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;color:#4DD0E1;">Physical</td><td style="padding:0.5rem;">Physics derivations, empirical grounding</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;color:#4DD0E1;">Biological</td><td style="padding:0.5rem;">Living systems, ecological modeling</td></tr></table><h3 style="color:#4DD0E1;">HILS Invariants</h3><p>Humans retain exclusive control over: pillar numbering, authorship claims, and falsification conditions.</p></div>')
        with gr.Tab("ECLIPSA"):
            gr.HTML('<div style="color:#E0E0E0;line-height:1.8;max-width:800px;margin:0 auto;"><h2 style="color:#FF9F00;">ECLIPSA Sentinel</h2><p>Epistemic Containment watchdog (spelling: E-C-L-I-P-S-A).</p><h3 style="color:#4DD0E1;">Enforcement</h3><ul><li>PII sanitization on all distilled insights</li><li>Contradiction gating against 208 hardgate pillars</li><li>Epistemic firewall \u2014 domain-tagged notes</li><li>Threat level monitoring (GREEN/AMBER/CRIMSON)</li><li>Audit reports and alert feed</li></ul><h3 style="color:#4DD0E1;">Three Gates</h3><ol><li>ECLIPSA PII sanitization</li><li>LLM distillation</li><li>Contradiction gate</li></ol></div>')
        with gr.Tab("PRODUCTS"):
            gr.HTML('<div style="color:#E0E0E0;max-width:900px;margin:0 auto;"><h2 style="color:#FF9F00;">Product Portfolio</h2><p>24 canonical products in the 12-AZ-IP portfolio.</p><table style="width:100%;border-collapse:collapse;font-size:0.85rem;"><tr style="border-bottom:1px solid #1F2933;"><th style="text-align:left;padding:0.5rem;color:#FF9F00;">#</th><th style="text-align:left;padding:0.5rem;color:#FF9F00;">Product</th><th style="text-align:left;padding:0.5rem;color:#FF9F00;">TRL</th></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;">01</td><td>AxiomOS</td><td>TRL-4</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;">02</td><td>AZ Kernel</td><td>TRL-3</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;">03</td><td>Eige (Election Guardian)</td><td>TRL-5</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;">04</td><td>UM-SOS</td><td>TRL-4</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;">08</td><td>AXIOM Journalist</td><td>TRL-4</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;">10</td><td>Filmer\'s Companion</td><td>TRL-3</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;">11</td><td>Terra OS</td><td>TRL-4</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;">13</td><td>DelPhi Oracle</td><td>TRL-5</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;">19</td><td>Falsification Observatory</td><td>TRL-5</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;">20</td><td>PsiCat Navigator</td><td>TRL-4</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;">21</td><td>Geo Monitor</td><td>TRL-5</td></tr><tr style="border-bottom:1px solid #1F2933;"><td style="padding:0.5rem;">22</td><td>AZ-SGE</td><td>TRL-4</td></tr></table></div>')
        with gr.Tab("LICENSE"):
            gr.HTML('<div style="color:#E0E0E0;line-height:1.8;max-width:800px;margin:0 auto;"><h2 style="color:#FF9F00;">License</h2><p>Defensive Public Commons License v1.0</p><h3 style="color:#4DD0E1;">Attribution</h3><p><b>Theory:</b> ThomasCory Walker-Pearson<br><b>Code:</b> PsiCat Navigator (AI)<br><b>Repository:</b> <a href="https://github.com/wuzbak/Unitary-Manifold-" style="color:#FF9F00;">github.com/wuzbak/Unitary-Manifold-</a></p></div>')

if __name__ == "__main__":
    app.launch(server_name="0.0.0.0", server_port=7860, share=False, show_error=True)
