load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_metric_bazel",
    srcs = ["test_metric.py"],
    imports = [".."],
    deps = [
        "//src/core:metric",
        "@pip//numpy",
        "@pip//pytest",
        "@pip//scipy",
    ],
)

py_test(
    name = "test_check_large_files",
    srcs = ["test_check_large_files.py"],
    data = ["//TOOLS/checks:check_large_files_py"],
    imports = [".."],
    deps = [
        "@pip//numpy",
        "@pip//pytest",
    ],
)
