# SPDX-License-Identifier: LicenseRef-Defensive-Public-Commons-1.0
# Copyright (C) 2026  ThomasCory Walker-Pearson

from src.core.pillar1114_lane4_falsifier_tension_discipline import (
    NEXT_PILLAR_SLOT,
    PILLAR_GATE,
    PILLAR_NUMBER,
    PILLAR_STATUS,
    lane4_falsifier_tension_discipline,
)


def test_identity() -> None:
    assert PILLAR_NUMBER == 1114
    assert PILLAR_GATE == 'LANE4_FALSIFIER_TENSION_DISCIPLINE'
    assert PILLAR_STATUS == 'LANE4_FALSIFIER_TENSION_DISCIPLINE_COMPLETE'
    assert NEXT_PILLAR_SLOT == 1115


def test_contract() -> None:
    report = lane4_falsifier_tension_discipline()
    assert report['outcome'] in {'LANE4_FALSIFIER_TENSION_DISCIPLINE_READY', 'LANE4_FALSIFIER_TENSION_DISCIPLINE_BLOCKED'} or report['outcome'] in {'SPRINT_CR_MASTER_CHARTER_READY','SPRINT_CR_MASTER_CHARTER_BLOCKED','SPRINT_CR_FORMAL_BURDEN_BOARD_READY','SPRINT_CR_FORMAL_BURDEN_BOARD_BLOCKED','LANE1_ACTION_TO_EVOLUTION_CLOSURE_ATTEMPT_READY','LANE1_ACTION_TO_EVOLUTION_CLOSURE_ATTEMPT_BLOCKED','LANE2_LEAN4_DETERMINISTIC_PROOF_READY','LANE2_LEAN4_DETERMINISTIC_PROOF_BLOCKED','LANE3_PYTHON_LEAN_TRUTH_EQUIVALENCE_READY','LANE3_PYTHON_LEAN_TRUTH_EQUIVALENCE_BLOCKED','LANE4_FALSIFIER_TENSION_DISCIPLINE_READY','LANE4_FALSIFIER_TENSION_DISCIPLINE_BLOCKED','LANE5_VERIFICATION_REGRESSION_DISCIPLINE_READY','LANE5_VERIFICATION_REGRESSION_DISCIPLINE_BLOCKED','SPRINT_CR_DOCUMENTATION_EVIDENCE_PACKET_READY','SPRINT_CR_DOCUMENTATION_EVIDENCE_PACKET_BLOCKED','SPRINT_CR_STATUS_COHERENCE_CERTIFICATE_READY','SPRINT_CR_STATUS_COHERENCE_CERTIFICATE_BLOCKED','SPRINT_CR_MASTER_INTEGRATION_CERTIFICATE_READY','SPRINT_CR_MASTER_INTEGRATION_CERTIFICATE_BLOCKED'}
    assert 'DESI_DR3_MONITORING' in report['open_lanes_unchanged']
