# SPDX-License-Identifier: LicenseRef-Defensive-Public-Commons-1.0
# Copyright (C) 2026  ThomasCory Walker-Pearson
from __future__ import annotations

import numpy as np

N_S = 0.9635
R_BRAIDED = 0.0315
BETA_LOW = 0.273
BETA_HIGH = 0.331
BETA_FLOOR = 0.22
BETA_CEILING = 0.38
BETA_FORBIDDEN_LOW = 0.29
BETA_FORBIDDEN_HIGH = 0.31
WINDING_NUMBER = 5
BRAID_PARTNER = 7
K_CS = 74
BRAIDED_SOUND_SPEED = 12.0 / 37.0
XI_C = 35.0 / 74.0
PHI_0 = 1.0
PHI_MIN = 0.0
PHI_MAX = 2.0
KK_MODE_COUNT = 10
KK_SPECTRAL_EXPONENT = 2
PLANCK_CENTER = np.array([0.9649, 0.0180], dtype=float)
CMB_X_RANGE = np.array([0.9520, 0.9720], dtype=float)
CMB_Y_RANGE = np.array([0.0000, 0.0400], dtype=float)
CMB_BICEP_KECK_BOUND = 0.036
DM21_TENSIONS = np.array([2.98, 1.16, 1.07], dtype=float)
LEAN4_THEOREMS = 1411
TEST_COUNT = 58563
PENROSE_ENTROPY_RATIO = 0.25
AREA_TO_ENTROPY_RATIO = 4.0
HOLOGRAPHIC_RADIUS = 1.0
BOUNDARY_POINT_COUNT = 360

UM_IMAGE_CONSTANTS = {
    "N_S": N_S,
    "R_BRAIDED": R_BRAIDED,
    "BETA_LOW": BETA_LOW,
    "BETA_HIGH": BETA_HIGH,
    "BETA_FLOOR": BETA_FLOOR,
    "BETA_CEILING": BETA_CEILING,
    "BETA_FORBIDDEN_LOW": BETA_FORBIDDEN_LOW,
    "BETA_FORBIDDEN_HIGH": BETA_FORBIDDEN_HIGH,
    "WINDING_NUMBER": WINDING_NUMBER,
    "BRAID_PARTNER": BRAID_PARTNER,
    "K_CS": K_CS,
    "BRAIDED_SOUND_SPEED": BRAIDED_SOUND_SPEED,
    "XI_C": XI_C,
    "PHI_0": PHI_0,
    "PHI_MIN": PHI_MIN,
    "PHI_MAX": PHI_MAX,
    "KK_MODE_COUNT": KK_MODE_COUNT,
    "KK_SPECTRAL_EXPONENT": KK_SPECTRAL_EXPONENT,
    "PLANCK_CENTER": PLANCK_CENTER.copy(),
    "CMB_X_RANGE": CMB_X_RANGE.copy(),
    "CMB_Y_RANGE": CMB_Y_RANGE.copy(),
    "CMB_BICEP_KECK_BOUND": CMB_BICEP_KECK_BOUND,
    "DM21_TENSIONS": DM21_TENSIONS.copy(),
    "LEAN4_THEOREMS": LEAN4_THEOREMS,
    "TEST_COUNT": TEST_COUNT,
    "PENROSE_ENTROPY_RATIO": PENROSE_ENTROPY_RATIO,
    "AREA_TO_ENTROPY_RATIO": AREA_TO_ENTROPY_RATIO,
    "HOLOGRAPHIC_RADIUS": HOLOGRAPHIC_RADIUS,
    "BOUNDARY_POINT_COUNT": BOUNDARY_POINT_COUNT,
}

__all__ = [name for name in UM_IMAGE_CONSTANTS] + ["UM_IMAGE_CONSTANTS"]
