# Copyright (C) 2026  ThomasCory Walker-Pearson
# SPDX-License-Identifier: LicenseRef-DefensivePublicCommons-1.0
"""
src/quantum/__init__.py
=======================
Quantum-circuit layer of the Unitary Manifold.

Current modules
---------------
kk_vqe
    Variational Quantum Eigensolver formulation of the Kaluza–Klein mass
    eigenvalue problem on the compact S¹ dimension with (5,7,74) braid
    corrections.
fermi_hubbard
    Adjacent-track Fermi–Hubbard model and mappings (JW/BK), execution,
    observables, and benchmark utilities.
xdiag_bridge
    Adjacent UM↔XDiag compatibility bridge for schema contracts, bidirectional
    artifact conversion, parity gates, and deterministic routing.
fh_solver
    Adjacent-track exact diagonalization (ED) solver for the 1D Fermi–Hubbard
    model with sector decomposition and Bethe Ansatz validation.
um_kk_fh_bridge
    Formal adjacent-track bridge mapping UM KK braid constants (5, 7, 74) to
    Fermi–Hubbard parameters; confirms the Mott insulating phase at U/t ≈ 78.
"""
from .fh_solver import (
    FHSectorResult,
    FHEdResult,
    solve_sector,
    exact_diagonalize,
    BETHE_ANSATZ_2SITE,
    validate_bethe_ansatz,
    um_kk_natural_parameters,
)
from .um_kk_fh_bridge import (
    KKFHBridgeResult,
    kk_to_fh_parameters,
    run_kk_fh_bridge,
    mott_insulator_verdict,
    BRIDGE_STATUS,
    KK_U_OVER_T,
    KK_PHASE,
)
from .kk_vqe import (
    kk_hamiltonian,
    ansatz_circuit,
    vqe_kk,
    VQEResult,
)
from .fermi_hubbard import (
    FermionTerm,
    FermiHubbardHamiltonian,
    build_fermi_hubbard_1d,
)
from .fermion_mapping import (
    PauliTerm,
    fermion_terms_to_qubit_terms,
    pauli_terms_to_matrix,
)
from .execution import (
    ExecutionConfig,
    ExecutionResult,
    MockHardwareAdapter,
    RunManifest,
    run_time_evolution,
    save_run_artifact,
)
from .benchmarks import (
    TDVPReference,
    TDVPParityReport,
    ScalingCurve,
    ScalingPoint,
    build_scaling_curve,
    run_observable_benchmark,
    tdvp_parity_report,
)
from .fh_lattice import (
    LatticeGeometry,
    FermiHubbardLattice,
    chain_1d_geometry,
    square_2d_geometry,
    cubic_3d_geometry,
    braid_kk_geometry,
    custom_geometry,
    build_fermi_hubbard_chain,
    build_fermi_hubbard_square_2d,
    build_fermi_hubbard_cubic_3d,
    build_fermi_hubbard_braid_kk,
    hilbert_space_dimension,
    memory_estimate_bytes,
    memory_estimate_gb,
    ADJACENCY_TRACK_LABEL,
    UM_BRAID_SITES,
    UM_BRAID_N1,
    UM_BRAID_N2,
)
from .fh_lattice_routing import (
    RoutingConfig,
    MemoryBudget,
    LatticeRoutingDecision,
    LatticeRoutingReport,
    lattice_route,
    preflight_check,
    geometry_routing_thresholds,
    scaling_estimate,
    ROUTE_UM_EXACT_DENSE,
    ROUTE_BRIDGE_CROSSCHECK,
    ROUTE_XDIAG_SPARSE,
)
from .fh_curved import (
    KK_RADION_COUPLING,
    KK_BRAIDED_SOUND_SPEED,
    KK_WINDING_NUMBER,
    CURVED_TRACK_LABEL,
    RadionField,
    CurvedSpaceFHSpec,
    KKCurvedGeometrySpec,
    CurvedFermiHubbardLattice,
    radion_hopping_factor,
    curved_hopping_coefficient,
    build_radion_field_uniform,
    build_radion_field_sinusoidal,
    build_radion_field_kk_natural,
    build_fermi_hubbard_curved,
    kk_curved_spec,
    separation_guard,
    curved_adjacency_report,
)
from .xdiag_bridge import (
    XDIAG_UM_SCHEMA_VERSION,
    CouplingSpec,
    EvolutionSpec,
    LatticeSpec as XDiagLatticeSpec,
    ObservableSpec,
    OPTIONAL_METRICS,
    ParityDelta,
    ParityReport,
    ParityTolerance,
    ProvenanceSpec,
    REQUIRED_METRICS,
    RoutingDecision,
    RoutingThresholds,
    SectorSpec,
    XDiagBridgeArtifact,
    XDiagBridgeSpec,
    XDiagExportPayload,
    assert_parity,
    assert_schema_version,
    build_xdiag_bridge_spec,
    choose_route,
    export_um_to_xdiag,
    ingest_xdiag_to_um_artifact,
    parity_report,
    production_health_check,
    save_bridge_artifact,
    spec_from_dict,
)

__all__ = [
    "kk_hamiltonian",
    "ansatz_circuit",
    "vqe_kk",
    "VQEResult",
    "FHSectorResult",
    "FHEdResult",
    "solve_sector",
    "exact_diagonalize",
    "BETHE_ANSATZ_2SITE",
    "validate_bethe_ansatz",
    "um_kk_natural_parameters",
    "KKFHBridgeResult",
    "kk_to_fh_parameters",
    "run_kk_fh_bridge",
    "mott_insulator_verdict",
    "BRIDGE_STATUS",
    "KK_U_OVER_T",
    "KK_PHASE",
    "FermionTerm",
    "FermiHubbardHamiltonian",
    "build_fermi_hubbard_1d",
    "PauliTerm",
    "fermion_terms_to_qubit_terms",
    "pauli_terms_to_matrix",
    "ExecutionConfig",
    "ExecutionResult",
    "MockHardwareAdapter",
    "RunManifest",
    "run_time_evolution",
    "save_run_artifact",
    "TDVPReference",
    "TDVPParityReport",
    "ScalingCurve",
    "ScalingPoint",
    "build_scaling_curve",
    "run_observable_benchmark",
    "tdvp_parity_report",
    # fh_lattice — geometry-aware multi-dimensional FH
    "LatticeGeometry",
    "FermiHubbardLattice",
    "chain_1d_geometry",
    "square_2d_geometry",
    "cubic_3d_geometry",
    "braid_kk_geometry",
    "custom_geometry",
    "build_fermi_hubbard_chain",
    "build_fermi_hubbard_square_2d",
    "build_fermi_hubbard_cubic_3d",
    "build_fermi_hubbard_braid_kk",
    "hilbert_space_dimension",
    "memory_estimate_bytes",
    "memory_estimate_gb",
    "ADJACENCY_TRACK_LABEL",
    "UM_BRAID_SITES",
    "UM_BRAID_N1",
    "UM_BRAID_N2",
    # fh_lattice_routing — geometry-aware routing and memory budgets
    "RoutingConfig",
    "MemoryBudget",
    "LatticeRoutingDecision",
    "LatticeRoutingReport",
    "lattice_route",
    "preflight_check",
    "geometry_routing_thresholds",
    "scaling_estimate",
    "ROUTE_UM_EXACT_DENSE",
    "ROUTE_BRIDGE_CROSSCHECK",
    "ROUTE_XDIAG_SPARSE",
    # fh_curved — curved-space FH scaffolding
    "KK_RADION_COUPLING",
    "KK_BRAIDED_SOUND_SPEED",
    "KK_WINDING_NUMBER",
    "CURVED_TRACK_LABEL",
    "RadionField",
    "CurvedSpaceFHSpec",
    "KKCurvedGeometrySpec",
    "CurvedFermiHubbardLattice",
    "radion_hopping_factor",
    "curved_hopping_coefficient",
    "build_radion_field_uniform",
    "build_radion_field_sinusoidal",
    "build_radion_field_kk_natural",
    "build_fermi_hubbard_curved",
    "kk_curved_spec",
    "separation_guard",
    "curved_adjacency_report",
    # xdiag_bridge — production-parity UM↔XDiag integration lane
    "XDIAG_UM_SCHEMA_VERSION",
    "XDiagLatticeSpec",
    "CouplingSpec",
    "SectorSpec",
    "ObservableSpec",
    "EvolutionSpec",
    "ProvenanceSpec",
    "XDiagBridgeSpec",
    "assert_schema_version",
    "build_xdiag_bridge_spec",
    "spec_from_dict",
    "XDiagExportPayload",
    "XDiagBridgeArtifact",
    "export_um_to_xdiag",
    "ingest_xdiag_to_um_artifact",
    "production_health_check",
    "save_bridge_artifact",
    "REQUIRED_METRICS",
    "OPTIONAL_METRICS",
    "ParityTolerance",
    "ParityDelta",
    "ParityReport",
    "parity_report",
    "assert_parity",
    "RoutingThresholds",
    "RoutingDecision",
    "choose_route",
]
