.PHONY: build debug release install clean test
build:
	cd android && ./gradlew assembleDebug
release:
	cd android && ./gradlew assembleRelease
install:
	cd android && ./gradlew installDebug
test:
	cd android && ./gradlew test
clean:
	cd android && ./gradlew clean
