.PHONY: build debug release install clean test lint
build:
	./gradlew assembleDebug
release:
	./gradlew assembleRelease
install:
	./gradlew installDebug
test:
	./gradlew test
lint:
	./gradlew lint
clean:
	./gradlew clean
