"""
build_context.py — Generate a portable knowledge snapshot from the full repository.

Usage:
  python bot/scripts/build_context.py                  # writes bot/context_snapshot.md
  python bot/scripts/build_context.py --out custom.md  # writes to custom path
  python bot/scripts/build_context.py --stats          # print stats only, no write

This script reads every document in the AGENTS.md ingest order and writes a
single consolidated markdown file.  That file can be:
  - Uploaded as a knowledge file to a Custom GPT or Claude Project
  - Committed as bot/context_snapshot.md and fetched by the Copilot Extension
    in environments where the full repo is not present on disk
  - Embedded in any other system that needs the full repository knowledge

Run this script whenever the repository content changes to keep the snapshot
current.  It is idempotent: running it twice produces the same output.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# File list — AGENTS.md Tier 1-4 ingest order
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).parent.parent.parent

INGEST_ORDER: list[tuple[str, str]] = [
    # (relative_path, tier_label)
    # Tier 1 — essential context, minimal tokens
    ("WHAT_THIS_MEANS.md",                       "Tier 1 — Core claim in plain language"),
    ("MCP_INGEST.md",                            "Tier 1 — Compact structured summary"),
    ("llms.txt",                                 "Tier 1 — AI discovery index"),
    ("CITATION.cff",                             "Tier 1 — Citation metadata"),
    ("schema.jsonld",                            "Tier 1 — JSON-LD structured data"),
    # Tier 2 — implementation context
    ("README.md",                                "Tier 2 — Full project overview"),
    ("UNIFICATION_PROOF.md",                     "Tier 2 — Formal unification proof"),
    ("QUANTUM_THEOREMS.md",                      "Tier 2 — New theorems XII-XV"),
    ("FALLIBILITY.md",                           "Tier 2 — Honest gaps and limitations"),
    ("BIG_QUESTIONS.md",                         "Tier 2 — Open scientific questions"),
    ("UNDERSTANDABLE_EXPLANATION.md",            "Tier 2 — Plain-language explanation"),
    ("LEGEND.md",                                "Tier 2 — Symbol legend"),
    ("RELAY.md",                                 "Tier 2 — Relay document"),
    # Tier 3 — wiki
    ("wiki/Home.md",                             "Tier 3 — Wiki home"),
    ("wiki/Field-Equations.md",                  "Tier 3 — Field equations wiki"),
    ("wiki/Mathematical-Framework.md",           "Tier 3 — Mathematical framework wiki"),
    ("wiki/Numerical-Methods.md",                "Tier 3 — Numerical methods wiki"),
    ("wiki/API-Reference.md",                    "Tier 3 — API reference wiki"),
    ("wiki/Getting-Started.md",                  "Tier 3 — Getting started wiki"),
    ("wiki/Monograph-Structure.md",              "Tier 3 — Monograph structure wiki"),
    # Tier 3 — manuscript & submission
    ("manuscript/ch02_mathematical_preliminaries.md", "Tier 3 — Mathematical preliminaries"),
    ("submission/one_page_summary.md",           "Tier 3 — One-page summary"),
    ("submission/falsification_report.md",       "Tier 3 — Falsification report"),
    ("docs/semantic-bridge.md",                  "Tier 3 — Semantic bridge"),
    # Tier 3 — review & discussions
    ("REVIEW_CONCLUSION.md",                     "Tier 3 — Review conclusion"),
    ("FINAL_REVIEW_CONCLUSION.md",               "Tier 3 — Final review conclusion"),
    ("discussions/AI-Automated-Review-Invitation.md", "Tier 3 — AI review invitation"),
    # Tier 4 — source code
    ("src/core/metric.py",                       "Tier 4 — metric.py source"),
    ("src/core/evolution.py",                    "Tier 4 — evolution.py source"),
    ("src/holography/boundary.py",               "Tier 4 — boundary.py source"),
    ("src/multiverse/fixed_point.py",            "Tier 4 — fixed_point.py source"),
]


def build_snapshot(verbose: bool = True) -> tuple[str, dict]:
    """Return (snapshot_text, stats_dict)."""
    sections: list[str] = []
    stats = {"loaded": 0, "skipped": 0, "total_chars": 0, "files": []}

    header = (
        "# Unitary Manifold — Full Repository Knowledge Snapshot\n\n"
        "> Generated by `bot/scripts/build_context.py`  \n"
        "> Ingest order follows `AGENTS.md` Tier 1-4 priority.  \n"
        "> Upload this file as knowledge to a Custom GPT or Claude Project.  \n"
        "> Re-run whenever repository content changes.\n\n"
        "---\n"
    )
    sections.append(header)

    for rel, label in INGEST_ORDER:
        full = REPO_ROOT / rel
        if not full.exists():
            if verbose:
                print(f"  SKIP  {rel}")
            stats["skipped"] += 1
            continue
        try:
            text = full.read_text(encoding="utf-8")
        except Exception as exc:
            if verbose:
                print(f"  ERR   {rel}: {exc}")
            stats["skipped"] += 1
            continue

        fence = "=" * 64
        lang = "python" if rel.endswith(".py") else ""
        section = (
            f"\n\n{fence}\n"
            f"FILE: {rel}\n"
            f"LABEL: {label}\n"
            f"{fence}\n\n"
            f"```{lang}\n{text}\n```"
        )
        sections.append(section)
        stats["loaded"] += 1
        stats["total_chars"] += len(text)
        stats["files"].append(rel)
        if verbose:
            print(f"  OK    {rel}  ({len(text):,} chars)")

    return "".join(sections), stats


def main() -> None:
    parser = argparse.ArgumentParser(description="Build Unitary Manifold knowledge snapshot")
    parser.add_argument("--out", default=None, help="Output path (default: bot/context_snapshot.md)")
    parser.add_argument("--stats", action="store_true", help="Print stats only, do not write")
    args = parser.parse_args()

    out_path = Path(args.out) if args.out else REPO_ROOT / "bot" / "context_snapshot.md"

    print("Building knowledge snapshot...")
    snapshot, stats = build_snapshot(verbose=not args.stats)

    print(f"\n{'─' * 50}")
    print(f"  Loaded : {stats['loaded']} files")
    print(f"  Skipped: {stats['skipped']} files")
    print(f"  Total  : {stats['total_chars']:,} characters  (~{stats['total_chars'] // 4:,} tokens)")
    print(f"{'─' * 50}")

    if args.stats:
        return

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(snapshot, encoding="utf-8")
    print(f"\n✅  Snapshot written to: {out_path}")
    print(f"   Upload this file to your Custom GPT or Claude Project knowledge base.")


if __name__ == "__main__":
    main()
