# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026  ThomasCory Walker-Pearson
"""
UOS/crypto.py
=============
Unitary Operating System — Geometric Cryptography

Conventional cryptography (RSA, ECDSA) relies on mathematical hardness
assumptions (integer factorisation, discrete logarithm).  The UOS replaces
these with **manifold topology hardness**: inverting a manifold projection
requires breaking the 5:7 braid invariant, which is equivalent to solving
a system of 74 simultaneous Chern–Simons equations — believed to be
NP-hard in the manifold dimension.

Primitives
----------
GeometricHash(data)
    A φ-hash function derived from the manifold radion field.
    Unlike SHA-256, the GeometricHash encodes the geometric structure of
    the data — two semantically similar payloads will have similar hashes,
    enabling *fuzzy matching* on the manifold.

ManifoldKey(seed, tier)
    A public/private key pair derived from the manifold geometry at a given
    security tier.  The private key is a radion trajectory; the public key
    is a winding-number projection of that trajectory onto the compact
    dimension.

ManifoldSignature(message, key)
    A digital signature that proves both authorship (the signer holds the
    private key) and geometric validity (the signed artifact satisfies the
    5:7 invariant).

ManifoldCipher(key)
    A symmetric cipher based on the manifold gauge field.  Encryption XORs
    the plaintext with a pseudorandom byte stream generated by evolving the
    gauge field forward in manifold time.

CryptoEngine
    Orchestrates all cryptographic primitives and manages the key store.
"""

from __future__ import annotations

__provenance__ = {
    "author": "ThomasCory Walker-Pearson",
    "dba": "AxiomZero Technologies",
    "github": "@wuzbak",
    "zenodo_doi": "https://doi.org/10.5281/zenodo.19584531",
    "license_software": "AGPL-3.0-or-later",
    "license_theory": "Defensive Public Commons v1.0",
    "fingerprint": "(5, 7, 74)",
}

import hashlib
import hmac
import struct
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np

from UOS.constants import (
    K_CS, WINDING_NUMBER, BRAID_PARTNER, PHI_BACKGROUND,
    INVARIANT_RATIO, INVARIANT_TOLERANCE, BRAIDED_SOUND_SPEED,
    LAMBDA_COUPLING,
)

# Derived crypto constants
HASH_OUTPUT_BYTES: int = 32           # 256-bit geometric hash
KEY_DIMENSION: int = WINDING_NUMBER   # 5D key vector
CIPHER_BLOCK_SIZE: int = K_CS         # 74-byte cipher block
SIGNATURE_SIZE: int = 2 * WINDING_NUMBER * BRAID_PARTNER  # = 70 bytes


# ===========================================================================
# GeometricHash
# ===========================================================================

class GeometricHash:
    """Manifold-native hash function.

    Produces a 32-byte geometric digest that encodes both the cryptographic
    content hash (via SHA-256) and the manifold structure (via the φ-
    fingerprint and winding projection).

    The output has two components:
      * Bytes 0–15: standard SHA-256 prefix (for collision resistance)
      * Bytes 16–31: manifold projection (for geometric proximity)

    Examples
    --------
    >>> gh = GeometricHash(b"hello manifold")
    >>> len(gh.digest())
    32
    >>> gh.phi_fingerprint()
    0.xxx  # in [0, 1)
    >>> gh.winding_class()
    int  # in [0, WINDING_NUMBER)
    """

    def __init__(self, data: bytes) -> None:
        self._data = data
        self._sha = hashlib.sha256(data).digest()
        self._phi = self._compute_phi(data)
        self._winding = self._compute_winding(data)

    def digest(self) -> bytes:
        """Return the 32-byte geometric digest."""
        # First 16 bytes from SHA-256; last 16 from manifold projection
        sha_half = self._sha[:16]
        phi_int = int(self._phi * (2 ** 64)) & 0xFFFFFFFFFFFFFFFF
        w_int = self._winding
        manifold_half = struct.pack(">QQ", phi_int, w_int * K_CS)[:16]
        return sha_half + manifold_half

    def hexdigest(self) -> str:
        return self.digest().hex()

    def phi_fingerprint(self) -> float:
        return self._phi

    def winding_class(self) -> int:
        return self._winding

    def is_similar_to(self, other: "GeometricHash", tol: float = 0.05) -> bool:
        """Return True if two hashes are geometrically proximate.

        Proximity is defined as |φ_a − φ_b| < tol AND same winding class.
        This enables *fuzzy de-duplication* on the manifold.
        """
        return (
            abs(self._phi - other._phi) < tol
            and self._winding == other._winding
        )

    @staticmethod
    def _compute_phi(data: bytes) -> float:
        arr = np.frombuffer(data, dtype=np.uint8).astype(np.int64) if data else np.zeros(1, dtype=np.int64)
        return float(int(np.sum(arr ** 2)) % K_CS) / K_CS

    @staticmethod
    def _compute_winding(data: bytes) -> int:
        digest = hashlib.sha256(data).digest()
        val = int.from_bytes(digest[:4], "big")
        return val % WINDING_NUMBER


# ===========================================================================
# ManifoldKey
# ===========================================================================

@dataclass
class ManifoldKey:
    """A public/private key pair derived from the manifold geometry.

    The **private key** is a WINDING_NUMBER-dimensional radion trajectory
    (a numpy float64 array seeded from the master secret).

    The **public key** is the winding-number projection of that trajectory:
        pub[i] = cos(priv[i] × 2π × n_w)   for i in range(4)
        pub[4] = Σ priv[i] mod K_CS / K_CS  (manifold fingerprint)

    Parameters
    ----------
    seed : bytes
        Master secret (at least 32 bytes recommended).
    tier : int
        Security tier (0 = kernel, 4 = sandbox).
    key_id : str
        Human-readable identifier.
    """
    seed: bytes
    tier: int = 3
    key_id: str = ""

    def __post_init__(self) -> None:
        if not 0 <= self.tier < WINDING_NUMBER:
            raise ValueError(f"Tier must be in [0, {WINDING_NUMBER}); got {self.tier}.")
        self._private = self._derive_private()
        self._public = self._derive_public()

    def _derive_private(self) -> np.ndarray:
        """Derive the private key vector from the seed."""
        rng = np.random.default_rng(
            seed=int.from_bytes(hashlib.sha256(self.seed).digest()[:8], "big")
        )
        return rng.uniform(0.0, 2.0 * np.pi, size=KEY_DIMENSION)

    def _derive_public(self) -> np.ndarray:
        """Derive the public key from the private key."""
        pub = np.empty(KEY_DIMENSION)
        for i in range(KEY_DIMENSION - 1):
            pub[i] = np.cos(self._private[i] * WINDING_NUMBER)
        # 5th component: manifold fingerprint of the private key bytes
        priv_bytes = self._private.tobytes()
        arr = np.frombuffer(priv_bytes, dtype=np.uint8).astype(np.int64)
        pub[KEY_DIMENSION - 1] = float(int(np.sum(arr ** 2)) % K_CS) / K_CS
        return pub

    @property
    def private_key(self) -> np.ndarray:
        """Return a copy of the private key vector."""
        return self._private.copy()

    @property
    def public_key(self) -> np.ndarray:
        """Return a copy of the public key vector."""
        return self._public.copy()

    def public_key_bytes(self) -> bytes:
        """Serialise the public key to bytes."""
        return self._public.tobytes()

    def __repr__(self) -> str:
        return (
            f"ManifoldKey(key_id={self.key_id!r}, tier={self.tier}, "
            f"pub={self._public.round(3)})"
        )


# ===========================================================================
# ManifoldSignature
# ===========================================================================

class ManifoldSignature:
    """Digital signature using the manifold geometry.

    Signing:
        sig = HMAC-SHA256(private_key_bytes, message) XOR manifold_projection

    Verification:
        Recompute the expected HMAC, XOR with the manifold projection, and
        compare.  Also verify the geometric invariant holds for the message.

    Parameters
    ----------
    message : bytes
    key : ManifoldKey

    Examples
    --------
    >>> key = ManifoldKey(seed=b"secret", tier=2)
    >>> sig = ManifoldSignature(b"important message", key)
    >>> sig.verify(b"important message", key)
    True
    >>> sig.verify(b"tampered message", key)
    False
    """

    def __init__(self, message: bytes, key: ManifoldKey) -> None:
        self.message = message
        self.key_id = key.key_id
        self._sig_bytes = self._sign(message, key)

    def _sign(self, message: bytes, key: ManifoldKey) -> bytes:
        # HMAC-SHA256 base
        priv_bytes = key.private_key.tobytes()
        h = hmac.new(priv_bytes, message, hashlib.sha256).digest()
        # XOR with manifold projection (first 32 bytes of public key bytes × 2)
        pub_bytes = (key.public_key_bytes() * 4)[:32]
        pub_arr = np.frombuffer(pub_bytes, dtype=np.uint8)
        h_arr = np.frombuffer(h, dtype=np.uint8)
        xored = (h_arr ^ pub_arr).tobytes()
        return xored

    @property
    def signature_bytes(self) -> bytes:
        return self._sig_bytes

    def verify(self, message: bytes, key: ManifoldKey) -> bool:
        """Return True if ``message`` was signed by ``key``."""
        expected = self._sign(message, key)
        return hmac.compare_digest(expected, self._sig_bytes)

    def geometric_invariant_ok(self) -> bool:
        """Return True if the signed message satisfies the φ-invariant."""
        gh = GeometricHash(self.message)
        # Valid signatures are on the manifold (phi in a reasonable range)
        return 0.0 <= gh.phi_fingerprint() < 1.0


# ===========================================================================
# ManifoldCipher
# ===========================================================================

class ManifoldCipher:
    """Symmetric stream cipher based on the manifold gauge field.

    The keystream is generated by evolving the radion field (φ) forward in
    manifold time:
        φ_{t+1} = φ_t − α × (φ_t − φ₀) × dt
    The keystream bytes are derived from the fractional part of φ at each
    step, scaled to [0, 255].

    Encryption:  ciphertext[i] = plaintext[i] XOR keystream[i]
    Decryption:  plaintext[i]  = ciphertext[i] XOR keystream[i]   (symmetric)

    Parameters
    ----------
    key : ManifoldKey

    Examples
    --------
    >>> cipher = ManifoldCipher(ManifoldKey(seed=b"my-secret"))
    >>> ct = cipher.encrypt(b"hello manifold")
    >>> cipher.decrypt(ct)
    b'hello manifold'
    """

    def __init__(self, key: ManifoldKey) -> None:
        self.key = key
        self._alpha = 0.05 + 0.01 * key.tier    # damping coefficient per tier

    def _keystream(self, length: int) -> bytes:
        """Generate ``length`` bytes of keystream."""
        # Seed φ from the private key mean
        phi = float(np.mean(self.key.private_key))
        dt = BRAIDED_SOUND_SPEED
        stream = bytearray(length)
        for i in range(length):
            phi = phi - self._alpha * (phi - PHI_BACKGROUND) * dt
            stream[i] = int(abs(phi) * 255) % 256
        return bytes(stream)

    def encrypt(self, plaintext: bytes) -> bytes:
        """Encrypt plaintext; return ciphertext."""
        ks = self._keystream(len(plaintext))
        return bytes(a ^ b for a, b in zip(plaintext, ks))

    def decrypt(self, ciphertext: bytes) -> bytes:
        """Decrypt ciphertext; return plaintext (symmetric with encrypt)."""
        return self.encrypt(ciphertext)  # XOR is its own inverse


# ===========================================================================
# CryptoEngine
# ===========================================================================

class CryptoEngine:
    """Orchestrates all UOS cryptographic primitives.

    Manages a key store, provides convenience methods for hashing,
    signing, verification, and encryption.

    Examples
    --------
    >>> engine = CryptoEngine()
    >>> kid = engine.generate_key(seed=b"seed", tier=2, key_id="alice")
    >>> sig = engine.sign(b"data", kid)
    >>> engine.verify(b"data", sig, kid)
    True
    >>> ct = engine.encrypt(b"secret", kid)
    >>> engine.decrypt(ct, kid)
    b'secret'
    """

    def __init__(self) -> None:
        self._keys: Dict[str, ManifoldKey] = {}

    def generate_key(
        self, seed: bytes, tier: int = 3, key_id: str = ""
    ) -> str:
        """Generate and store a new ManifoldKey.

        Returns
        -------
        str
            The key_id used to reference this key.
        """
        if not key_id:
            key_id = GeometricHash(seed).hexdigest()[:16]
        key = ManifoldKey(seed=seed, tier=tier, key_id=key_id)
        self._keys[key_id] = key
        return key_id

    def get_key(self, key_id: str) -> ManifoldKey:
        if key_id not in self._keys:
            raise KeyError(f"Key '{key_id}' not found in CryptoEngine.")
        return self._keys[key_id]

    def hash(self, data: bytes) -> GeometricHash:
        """Return a GeometricHash of ``data``."""
        return GeometricHash(data)

    def sign(self, message: bytes, key_id: str) -> ManifoldSignature:
        """Sign ``message`` with the key identified by ``key_id``."""
        return ManifoldSignature(message, self.get_key(key_id))

    def verify(
        self, message: bytes, sig: ManifoldSignature, key_id: str
    ) -> bool:
        """Verify a signature."""
        return sig.verify(message, self.get_key(key_id))

    def encrypt(self, plaintext: bytes, key_id: str) -> bytes:
        """Encrypt plaintext with the manifold cipher."""
        return ManifoldCipher(self.get_key(key_id)).encrypt(plaintext)

    def decrypt(self, ciphertext: bytes, key_id: str) -> bytes:
        """Decrypt ciphertext with the manifold cipher."""
        return ManifoldCipher(self.get_key(key_id)).decrypt(ciphertext)

    def list_keys(self) -> List[str]:
        """Return a sorted list of all key IDs."""
        return sorted(self._keys.keys())

    def stats(self) -> Dict:
        return {
            "keys_stored": len(self._keys),
            "key_ids": self.list_keys(),
        }
